### ISSUE TITLE
Base.css for various device-sizes.

### ISSUE THREAD

**Issue by dhvenema** [Geonovum/respec#102]
On a small screen the documentation in a respec-layout is harder to read, due to font-sizes not changes according to device-size. This could be accomplished by using CSS Grid Layout (or Skel module) to create more responsive layouts.

And, adjust css according to device-size:
```css
.class {
    height: 2.5em;
}

    @media screen and (max-width: 980px) {
        .class {
            height: 2em;
        }
    }

    @media screen and (max-width: 764px) {
        .class {
            height: 1.5em;
        }
    }

    @media screen and (max-width: 480px) {
        .class{
            height: 1em;
        }
    }
```
