### ISSUE TITLE
Change copyright section

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/respec#2]
W3C specific copyright section needs to be removed. Geonovum only uses a license statement: 

Licentie: http://creativecommons.org/licenses/by-nd/3.0/nl/.

**Comment by marcoscaceres** [comment]
Just a general comment: it's important to never change existing files in the "develop" branch, otherwise we will end up with perpetual merge conflicts with Git (and Geonovum won't be able to benefit from any upstream bug fixes).

Instead, I suggest making a "src/geonovum/" (or just "src/geo/"?)  and copy/pasting any files you want to modify into there. Then, you can just load them directly in the profile by changing the name from, for example, "w3c/headers" to "geo/headers".

**Comment by marcoscaceres** [comment]
Ah, just noticed you have created a "js/geonovum" and a "src/geonovum" folder. Excellent!

**Comment by lvdbrink** [comment]
Note to self: this is how the copyright statement should be. 

![licentiegn](https://cloud.githubusercontent.com/assets/7943515/23365125/190230ea-fd02-11e6-9f3a-70994f065537.png)

With the image hyperlinking to https://creativecommons.org/licenses/by-nd/3.0/nl/

**Comment by dhvenema** [comment]
This has been added to [headers.html](https://github.com/Geonovum/respec/blob/develop/js/geonovum/templates/headers.html). However, there's a thin grey line below the image and I'm not sure why. Any ideas @marcoscaceres?

**Comment by marcoscaceres** [comment]
@dhvenema, seems to be coming from base.css 

On line 509:

```CSS
a[href] {
    color: #034575;
    text-decoration: none;
    border-bottom: 1px solid #707070;
    padding: 0 1px 0;
    margin: 0 -1px 0;
}
```

**Comment by marcoscaceres** [comment]
Just noting you should probably make sure that the alt="" for the text has the text "Naamsvermelding-GeenAfgeleideWerken 3.0 ...", otherwise, it won't be accessible to users who rely on screen readers.

**Comment by marcoscaceres** [comment]
To fix the underline, you probably want to override the copyright rule of base so it doesn't add the border.

something like: 
```CSS
 .copyright a[href],  .copyright a[href]:hover {
   border: none;
}

```
