### ISSUE TITLE
Add "save as PDF"-button

### ISSUE THREAD

**Issue by dhvenema** [Geonovum/respec#60]
Some users would like the option to save the HTML as a PDF-file. Possible libraries for this could be:
* phantomJS
* jsPDF

**Comment by marcoscaceres** [comment]
Is this mainly for old IE users? I think all modern browsers have a "Print/Save as PDF" built in.

**Comment by dhvenema** [comment]
I'm not sure where the question came from. Perhaps the built-in save as PDF will suffice. I do believe they might want a 'prettier' PDF file as opposed to a print of the actual html.

**Comment by marcoscaceres** [comment]
@dhvenema, I see. We do have some control over the print style, via CSS print-specific styles (which would make any produced PDF "prettier" - could include particular page breaks or larger font, or the removal of certain things... we already do that, like prevent the ReSpec pill from being printed, etc.).

**Comment by dhvenema** [comment]
Could at least add something like this:
```css
@media print {
  section > h2,
  nav > h2 {
    page-break-before: always;
  }
  html {
    font-size: 12pt;
  }
  figure.scalable img[hidden] {
    display: block;
  }
}
```
